### PR TITLE
Move Bundling from Webpack to Rollup

### PR DESCRIPTION
**Pull request by k15a**
The UMD build from Webpack contains a reference to the window variable which breaks this package in NodeJS. As we are developing universal applications that run in the browser and NodeJS, it would be great if you could move from Webpack to Rollup.

### CODE REVIEW

**Comment by k15a** [comment]
Thanks for merging my changes so quickly. Would you mind releasing a new version to NPM?

**Comment by jimmywarting** [comment]
sure, later when i get home from work

**Comment by ofqwx** [comment]
Any update about this?

**Comment by jimmywarting** [comment]
i tried running the test and it failed due to `babel-plugin-transform-async-to-promises`
it returns a polyfilled promise version without a `.catch` mehtod

**Comment by jimmywarting** [comment]
should use the builtin promise instead of creating a own

**Pull request merged**
